map_account_type = {
    "100-7": "Operator Holding Account",
    "120-0": "Former Operator Holding Account",
    "100-9": "Aircraft Operator Account",
    "100-8": "Person Holding Account",
    "121-0": "Person Account in National Registry",
    "100-12": "Trading Account",
    "100-13": "Auction Delivery Account",
    "0-10": "Verifier Account",
    "0-11": "External Platform Holding Account",
    "110-0": "Pending Account",
    "100-0": "Party Holding Account",
    "100-2": "National Allowance Holding Account",
    "100-5": "Union Allowance Deletion Account",
    "100-14": "Auction Account",
    "100-15": "Aviation Auction Account",
    "100-16": "Total Quantity Account",
    "100-17": "Aviation Total Quantity Account",
    "100-18": "New Entrant Reserve Account",
    "100-19": "Special Reserve Account",
    "100-20": "Allocation Account",
    "100-21": "Aviation Allocation Account",
    "100-1": "AAU Deposit Account",
    "100-3": "Central Clearing Account",
    "100-4": "Gateway Deposit Account",
    "100-24": "AEA Total quantity Account",
    "280-0": "Ambition Increase Cancellation Account (Type 8)",
    "270-0": "Article 3.7ter Cancellation Account (Type 7)",
    "241-0": "CCS Net Reversal Cancellation Account",
    "130-0": "Previous Period Surplus Reserve Account (PPSR)",
    "100-6": "Aviation Surrender Set-Aside Account",
    "100-25": "ESD Compliance Account",
    "210-0": "Net Source Cancellation Account (Type 1)",
    "100-26": "AEA Deletion Account",
    "220-0": "Non-compliance Cancellation Account (Type 2)",
    "230-0": "Voluntary Cancellation Account (Type 3)",
    "240-0": "Excess Issuance Cancellation Account (Type 4)",
    "250-0": "Mandatory (Cancellation Account (Type 5)",
    "300-0": "Retirement Account",
    "411-0": "tCER Replacement Account for Expiry (Type 1)",
    "421-0": "lCER Replacement Account for Expiry (Type 1)",
    "422-0": "lCER Replacement Account for Reversal in Storage (Type 2)",
    "423-0": (
        "lCER Replacement Account for Non-submission of Certification Report (Type 3)"
    ),
    "100-27": "EU AAU Account",
    "100-31": "ETS Central Clearing Account for CP2",
    "100-29": "ESD Central Clearing Account",
    "100-28": "ETS AAU Deposit Account",
    "100-30": "ESD AAU Deposit Account",
    "242-0": "Non Submission Of Verification Report Cancellation Account",
    "100-22": "International Credit Account",
    "100-23": "Credit Exchange Account",
    # ESD accounts
    "esd": "EU Effort Sharing Account",
    # TODO can we add a real account type id?
    "maritime": "Maritime Operator Holding Account",
}

map_account_type_inv = {v: k for k, v in map_account_type.items()}


map_registryCodes = {
    "AT": "Austria",
    "BE": "Belgium",
    "BG": "Bulgaria",
    "HR": "Croatia",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "ED": "ESD",
    "EE": "Estonia",
    "EU": "European Commission",
    "FI": "Finland",
    "FR": "France",
    "DE": "Germany",
    "GR": "Greece",
    "HU": "Hungary",
    "IS": "Iceland",
    "IE": "Ireland",
    "IT": "Italy",
    "LV": "Latvia",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MT": "Malta",
    "NL": "Netherlands",
    "NO": "Norway",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "ES": "Spain",
    "SE": "Sweden",
    "GB": "United Kingdom",
    "AF": "Afghanistan",
    "AX": "Aland Islands",
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarctica",
    "AG": "Antigua And Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BQ": "Bonaire, Sint Eustatius and Saba",
    "BA": "Bosnia And Herzegovina",
    "BW": "Botswana",
    "BV": "Bouvet Island",
    "BR": "Brazil",
    "IO": "British Indian Ocean Territory",
    "BN": "Brunei Darussalam",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "CDM": "CDM",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CV": "Cape Verde",
    "KY": "Cayman Islands",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CX": "Christmas Island",
    "CC": "Cocos (Keeling) Islands",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": "Congo",
    "CD": "Congo, The Democratic Republic Of The",
    "CK": "Cook Islands",
    "CR": "Costa Rica",
    "CI": "Cote D&#39;Ivoire",
    "CU": "Cuba",
    "CW": "Curacao",
    "CY0": "Cyprus CP0",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "ET": "Ethiopia",
    "FK": "Falkland Islands (Malvinas)",
    "FO": "Faroe Islands",
    "FJ": "Fiji",
    "GF": "French Guiana",
    "PF": "French Polynesia",
    "TF": "French Southern Territories",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Heard Island And Mcdonald Islands",
    "VA": "Holy See (Vatican City State)",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "ITL": "ITL",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran, Islamic Republic Of",
    "IQ": "Iraq",
    "IL": "Israel",
    "JM": "Jamaica",
    "JP": "Japan",
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KP": "Korea, Democratic People&#39;S Republic Of",
    "KR": "Korea, Republic Of",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Lao People&#39;S Democratic Republic",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libyan Arab Jamahiriya",
    "MO": "Macao",
    "MK": "Macedonia, The Former Yugoslav Republic Of",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT0": "Malta CP0",
    "MH": "Marshall Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexico",
    "FM": "Micronesia, Federated States Of",
    "MD": "Moldova, Republic Of",
    "MC": "Monaco",
    "MN": "Mongolia",
    "MS": "Montserrat",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MP": "Northern Mariana Islands",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestinian Territory, Occupied",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PN": "Pitcairn",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RE": "Reunion",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "BL": "Saint Barthelemy",
    "SH": "Saint Helena",
    "KN": "Saint Kitts And Nevis",
    "LC": "Saint Lucia",
    "MF": "Saint Martin (French part)",
    "PM": "Saint Pierre And Miquelon",
    "VC": "Saint Vincent And The Grenadines",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome And Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "CS": "Serbia And Montenegro",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SX": "Sint Maarten (Dutch part)",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "GS": "South Georgia And The South Sandwich Islands",
    "SS": "South Sudan",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SJ": "Svalbard And Jan Mayen",
    "SZ": "Swaziland",
    "CH": "Switzerland",
    "SY": "Syrian Arab Republic",
    "TW": "Taiwan, Province Of China",
    "TJ": "Tajikistan",
    "TZ": "Tanzania, United Republic Of",
    "TH": "Thailand",
    "TL": "Timor-Leste",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad And Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": "Turks And Caicos Islands",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "US": "United States",
    "UM": "United States Minor Outlying Islands",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Viet Nam",
    "VG": "Virgin Islands, British",
    "VI": "Virgin Islands, U.S.",
    "WF": "Wallis And Futuna",
    "EH": "Western Sahara",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
    "XI": "Northern Ireland",
    "ESD": "Effort Sharing Management",
    "ME": "Montenegro",
    "RS": "Serbia",
    "IM": "Isle of Man",
}

map_registryCode_inv = {v: k for k, v in map_registryCodes.items()}
