map_account_type = {
    "100-7": "Operator Holding Account",
    "120-0": "Former Operator Holding Account",
    "100-9": "Aircraft Operator Account",
    "100-8": "Person Holding Account",
    "121-0": "Person Account in National Registry",
    "100-12": "Trading Account",
    "100-13": "Auction Delivery Account",
    "0-10": "Verifier Account",
    "0-11": "External Platform Holding Account",
    "110-0": "Pending Account",
    "100-0": "Party Holding Account",
    "100-2": "National Allowance Holding Account",
    "100-5": "Union Allowance Deletion Account",
    "100-14": "Auction Account",
    "100-15": "Aviation Auction Account",
    "100-16": "Total Quantity Account",
    "100-17": "Aviation Total Quantity Account",
    "100-18": "New Entrant Reserve Account",
    "100-19": "Special Reserve Account",
    "100-20": "Allocation Account",
    "100-21": "Aviation Allocation Account",
    "100-1": "AAU Deposit Account",
    "100-3": "Central Clearing Account",
    "100-4": "Gateway Deposit Account",
    "100-24": "AEA Total quantity Account",
    "280-0": "Ambition Increase Cancellation Account (Type 8)",
    "270-0": "Article 3.7ter Cancellation Account (Type 7)",
    "241-0": "CCS Net Reversal Cancellation Account",
    "130-0": "Previous Period Surplus Reserve Account (PPSR)",
    "100-6": "Aviation Surrender Set-Aside Account",
    "100-25": "ESD Compliance Account",
    "210-0": "Net Source Cancellation Account (Type 1)",
    "100-26": "AEA Deletion Account",
    "220-0": "Non-compliance Cancellation Account (Type 2)",
    "230-0": "Voluntary Cancellation Account (Type 3)",
    "240-0": "Excess Issuance Cancellation Account (Type 4)",
    "250-0": "Mandatory (Cancellation Account (Type 5)",
    "300-0": "Retirement Account",
    "411-0": "tCER Replacement Account for Expiry (Type 1)",
    "421-0": "lCER Replacement Account for Expiry (Type 1)",
    "422-0": "lCER Replacement Account for Reversal in Storage (Type 2)",
    "423-0": "lCER Replacement Account for Non-submission of Certification Report (Type 3)",
    "100-27": "EU AAU Account",
    "100-31": "ETS Central Clearing Account for CP2",
    "100-29": "ESD Central Clearing Account",
    "100-28": "ETS AAU Deposit Account",
    "100-30": "ESD AAU Deposit Account",
    "242-0": "Non Submission Of Verification Report Cancellation Account",
    "100-22": "International Credit Account",
    "100-23": "Credit Exchange Account",
    # ESD accounts
    "esd": "EU Effort Sharing Account",
    # TODO can we add a real account type id?
    "maritime": "Maritime Operator Holding Account",
}

map_account_type_inv = {v: k for k, v in map_account_type.items()}
